import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar, SidebarBody, SidebarLink } from "@/components/ui/sidebar"; // Adjust path as necessary
import { IconWallet, IconInfoCircle } from "@tabler/icons-react"; // Import necessary icons
import { FaEthereum } from "react-icons/fa";
import { SiSolidity } from "react-icons/si";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { label: "Solana", href: "/solana/wallet", icon: <SiSolidity /> },
  { label: "Ethereum", href: "/etherium/wallet", icon: <FaEthereum /> },
  { label: "About", href: "/about", icon: <IconInfoCircle /> },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar>
          <SidebarBody>
            <div className="flex flex-col gap-4">
              {links.map((link, index) => (
                <SidebarLink key={index} link={link} />
              ))}
            </div>
          </SidebarBody>
        </Sidebar>
        <div className="">{children}</div>
      </body>
    </html>
  );
}
